services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: ${DOMAIN}
      DATABASE_URL: mysql://vaultwardenuser:${MARIADB_PASSWORD}@localhost:3306/vaultwarden
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      SIGNUPS_DOMAINS_WHITELIST: uni-bremen.de
      SIGNUPS_ALLOWED: false
      SMTP_HOST: "smtp.uni-bremen.de"
      SMTP_SECURITY: "force_tls"
      SMTP_PORT: 465
      SMTP_FROM: "vaultwarden@neuro.uni-bremen.de"
      SMTP_FROM_NAME: "Vaultwarden @ University of Bremen"
      SMTP_USERNAME: ${EMAIL_USERNAME}
      SMTP_PASSWORD: ${EMAIL_PASSWORD}
      SMTP_AUTH_MECHANISM: "Plain"
      SMTP_TIMEOUT: 15
      SMTP_ACCEPT_INVALID_CERTS: true
      SMTP_ACCEPT_INVALID_HOSTNAMES: false
      SMTP_DEBUG: false
      SIGNUPS_VERIFY: true
      INVITATIONS_ALLOWED: false
      EMAIL_CHANGE_ALLOWED: false
    volumes:
      - "vaultwarden_vol:/data"
      - "/mariadb_socket:/run/mysqld"
    expose:
      - 80
    networks:
      - vaultwarden-network

volumes:
  vaultwarden_vol:

networks:
  vaultwarden-network:
    external: true

