services:
  smtpd:
    image: "wodby/opensmtpd"
    container_name: "smtpd"
    hostname: "smtpd"
    restart: always
    ports:
      - "25:25/tcp"
    environment:
      # I use a modified template. Thus gone... 
      RELAY_HOST: "XXX"
      RELAY_PROTO: "smtps"
      # I use a modified template. Thus gone... 
      RELAY_PORT: "XXX"
      RELAY_USER: ${EMAIL_USERNAME}
      RELAY_PASSWORD: ${EMAIL_PASSWORD}
    volumes:
      - "/root/smtpd/smtpd_pre.conf:/etc/gotpl/smtpd.conf.tmpl"
      - "smtpd_spool:/var/spool/smtpd"
    network_mode: bridge

volumes:
  smtpd_spool:
